### ISSUE TITLE
Build script failed !

### ISSUE THREAD

**Issue by gugansankar** [raintank/raintank-docker#82] opened 2016-09-22 12:53 UTC
Build script failed with the below mentioned error. When I check the requested package , its not there. it says 404 error [ https://github.com/raintank/metrictank/metricdef ] . But you have included in the config "https://github.com/raintank/inspect/blob/master/graphitewatcher/main.go#L7"

Please help me on this. Thanks in Advance

![raintank1](https://cloud.githubusercontent.com/assets/4958813/18748808/9aedc372-80f1-11e6-95c6-b9f758efb1c9.png)

**Comment by gugansankar** [comment] 2016-09-24 05:47
Any chance to look into this error?.  Thanks in Advance.

**Comment by Dieterbe** [comment] 2016-10-04 11:31
hey @gugansankar , i was on vacation, but i fixed graphitewatcher to work with a new library and it now builds fine.

**Comment by gugansankar** [comment] 2016-10-04 11:37
Thank you so much. Will check it and get back to you if hit with any errors

**Comment by gugansankar** [comment] 2016-10-04 12:47
I run the script on fresh machine. Now again , its stopped at nodejsgo container build

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 84 77.6M   84 65.9M    0     0  8616k      0  0:00:09  0:00:07  0:00:02 10.2Mtar: go/src/internal/syscall/unix: Cannot mkdir: Input/output error
tar: go/src/internal/syscall/unix: Cannot mkdir: Input/output error
tar: go/src/internal/syscall/unix/getentropy_openbsd.go: Cannot open: No such file or directory
tar: go/src/internal/syscall/unix: Cannot mkdir: Input/output error
tar: go/src/internal/syscall/unix/getrandom_linux.go: Cannot open: No such file or directory
tar: go/src/internal/syscall/unix: Cannot mkdir: Input/output error
tar: go/src/internal/syscall/unix/getrandom_linux_386.go: Cannot open: No such file or directory
tar: go/src/internal/syscall/unix: Cannot mkdir: Input/output error
tar: go/src/internal/syscall/unix/getrandom_linux_amd64.go: Cannot open: No such file or directory
.....

tar: go/test: Cannot mkdir: Invalid argumentcd Se  
ls

tar: go/test/utf.go: Cannot open: No such file or directory
tar: go/test: Cannot mkdir: Invalid argument
tar: go/test/varerr.go: Cannot open: No such file or directory
tar: go/test: Cannot mkdir: Invalid argument
tar: go/test/varinit.go: Cannot open: No such file or directory
tar: go/test: Cannot mkdir: Invalid argument
tar: go/test/writebarrier.go: Cannot open: No such file or directory
tar: go/test: Cannot mkdir: Invalid argument
tar: go/test/zerodivide.go: Cannot open: No such file or directory
tar: Exiting with failure status due to previous errors
The command '/bin/sh -c curl -SL https://storage.googleapis.com/golang/go1.7rc1.linux-amd64.tar.gz     | tar -xzC /usr/local' returned a non-zero code: 2
ERROR: failed building nodejsgo. stopping.
[root@srv1 raintank-docker]#

**Comment by Dieterbe** [comment] 2016-10-04 13:04
any chance your hard drive ran full? that's what this looks like.

**Comment by gugansankar** [comment] 2016-10-04 13:06
No, I have enough space in the server.

[root@srv1 raintank-docker]# df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/vg_hglogsrt-lv_root
                       50G  6.2G   41G  14% /
tmpfs                 3.9G     0  3.9G   0% /dev/shm
/dev/sda1             477M   51M  401M  12% /boot
/dev/mapper/vg_hglogsrt-lv_home
                       41G   48M   39G   1% /home
[root@srv1 raintank-docker]#

**Comment by Dieterbe** [comment] 2016-10-04 13:19
hmm weird. anyway this looks more like a problem with the underlying host/software - like perhaps a hard drive or filesystem error - not with our dockerfiles or scripts.  can you check the log of your docker daemon, or perhaps `dmesg` or /var/log/syslog?

**Comment by Dieterbe** [comment] 2016-10-04 14:19
i just deleted all my docker images and rebuilt everything from scratch without problems. which docker version and kernel do you use? i'm on docker 1.12.1 and kernel 4.7.5, but earlier versions should work too, if not too old.

**Comment by gugansankar** [comment] 2016-10-04 14:47
Server Specification : 
OS : CentOS 6.8
Kernel : 2.6.32-642.4.2.el6.x86_64
Docker : 1.7.1

# Now script stopped at this Eventtank.

```
 ---> Running in c529d3d222c1
cd /go/src/github.com/mattbaird/elastigo; git submodule update --init --recursive
Submodule 'cookbooks/apt' (https://github.com/opscode-cookbooks/apt.git) registered for path 'cookbooks/apt'
Submodule 'cookbooks/elasticsearch' (https://github.com/mattbaird/elasticsearch-chef.git) registered for path 'cookbooks/elasticsearch'
Submodule 'cookbooks/java' (https://github.com/cookbooks/java.git) registered for path 'cookbooks/java'
Cloning into 'cookbooks/apt'...
error: unable to create file test/kitchen/cookbooks/apt_test/README.md (Invalid argument)
fatal: cannot create directory at 'test/kitchen/cookbooks/apt_test/files': Invalid argument
Cloning into 'cookbooks/elasticsearch'...
/go/src/github.com/mattbaird/elastigo/.git/modules/cookbooks/elasticsearch/objects: Invalid argument
fatal: clone of 'https://github.com/mattbaird/elasticsearch-chef.git' into submodule path 'cookbooks/elasticsearch' failed
package github.com/mattbaird/elastigo/lib: exit status 128
- cd .; git clone https://github.com/philhofer/fwd /go/src/github.com/philhofer/fwd
Cloning into '/go/src/github.com/philhofer/fwd'...
error: unable to create directory for /go/src/github.com/philhofer/fwd/.git/logs/refs/remotes/origin/HEAD: Invalid argument
fatal: update_ref failed for ref 'HEAD': Cannot update the ref 'refs/heads/master': unable to create directory for /go/src/github.com/philhofer/fwd/.git/logs/refs/heads/master: Invalid argument
package github.com/philhofer/fwd: exit status 128
- cd .; git clone https://gopkg.in/alexcesaro/statsd.v1 /go/src/gopkg.in/alexcesaro/statsd.v1
Cloning into '/go/src/gopkg.in/alexcesaro/statsd.v1'...
error: unable to create temporary file: Invalid argument
fatal: failed to write object
fatal: unpack-objects failed
package gopkg.in/alexcesaro/statsd.v1: exit status 128
- cd .; git clone https://github.com/rakyll/globalconf /go/src/github.com/rakyll/globalconf
Cloning into '/go/src/github.com/rakyll/globalconf'...
error: unable to create directory for /go/src/github.com/rakyll/globalconf/.git/refs/remotes/origin/HEAD
fatal: update_ref failed for ref 'HEAD': Cannot update the ref 'refs/heads/master': unable to create directory for /go/src/github.com/rakyll/globalconf/.git/logs/refs/heads/master: Invalid argument
package github.com/rakyll/globalconf: exit status 128
The command '/bin/sh -c go get github.com/raintank/eventtank' returned a non-zero code: 1
ERROR: failed building eventtank. stopping.
[root@hglogs-rt raintank-docker]#
```

**Comment by Dieterbe** [comment] 2016-10-04 17:51
while different errors, i suspect the cause is the same. looks like disk/filesystem io errors. check the system logs, dmesg, docker log etc.
if you can upgrade docker to a more recent version, that might help too.

**Comment by gugansankar** [comment] 2016-10-04 18:16
thanks for your kind replies.

Now I changed my server OS to Ubuntu. this time build and setup scripts are completed without any issue. 
But when I run launch_dev.sh script , its show below.

root@ubuntu:~/raintank-docker# ./launch_dev.sh 
cleaning logs...
docker-compose bringing up containers...
Service "version" doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
root@ubuntu:~/raintank-docker# 

If I comment "version 2" in fig-dev.yaml and run the launch_dev.sh script, it shows some service are unsupported.

root@ubuntu:~/raintank-docker# ./launch_dev.sh 
cleaning logs...
docker-compose bringing up containers...
Unsupported config option for services service: 'graphiteMetrictank'
root@ubuntu:~/raintank-docker# 

I've one question here, In fig-dev.yaml you have mentioned to use "https://github.com/raintank/raintank-docker/blob/master/docker/fig-dev.yaml#L51" and "https://github.com/raintank/raintank-docker/blob/master/docker/fig-dev.yaml#L62"  

but there is no docker images created for these services. Even there is no Dockerfile present in the folder [ " https://github.com/raintank/raintank-docker/tree/master/docker/metrictank " , " https://github.com/raintank/raintank-docker/tree/master/docker/graphitewatcher " ]

**Comment by Dieterbe** [comment] 2016-10-04 18:26
for metrictank it should automatically pull the right image from https://hub.docker.com/r/raintank/metrictank/
for graphitewatcher there is a dockerfile in the directory, so it should have been created when you ran `./build_all.sh`, does it show up when you run `docker images | grep raintank` ?

regarding the launch_dev.sh output and fig-dev.yaml, i suspect that maybe your docker-compose is too old. just a guess though. which version of docker-compose do you have?

**Comment by gugansankar** [comment] 2016-10-04 18:32
Docker-Composer version:
root@ubuntu:~/raintank-docker# docker-compose --version
docker-compose 1.1.0
root@ubuntu:~/raintank-docker# 

For graphiteMetrictank :  there is no Docker file present the folder. but its called in fig-dev.yaml " https://github.com/raintank/raintank-docker/blob/master/docker/fig-dev.yaml#L114" 

Output of docker images:

![rain1](https://cloud.githubusercontent.com/assets/4958813/19087138/9b15b778-8a8e-11e6-936e-8b952dcb2f8e.png)

**Comment by Dieterbe** [comment] 2016-10-04 18:42
the graphiteMetrictank service uses the raintank/graphite-metrictank image which lives at https://hub.docker.com/r/raintank/graphite-metrictank/

don't worry, it will be automatically pulled in when needed (just like the metrictank image)
but that doesn't happen yet because of the current error..

the error `Unsupported config option for services service: 'graphiteMetrictank'` is quite vague and I don't understand it.
I think you have two options:
1) since docker-compose 1.1.0 is from february 2015 this is quite old. unfortunately the docker ecosystem evolves quite fast and some distros are not good at keeping up.  i hope you can easily upgrade to a more recent version and try again. i think a lot has changed since then and now. especially the syntax of the config file
2) if upgrading is not an option, you could seek help with the docker/docker-compose folks and figure out more details about what's wrong, maybe you can adjust the config file to workaround the problem. but i suspect they'll also just tell you to upgrade.

**Comment by gugansankar** [comment] 2016-10-04 19:49
Yes, that error message got resolved once I upgrade it.

But still received the below error message at last. Also, containers are started but not sure all the containers are started. Since I couldn't see the port 3000 listening in the server.

Error Message:
![rain2](https://cloud.githubusercontent.com/assets/4958813/19089887/b52d802c-8a99-11e6-8f94-a4bda4f33cdf.png)

Containers started in the server:
root@ubuntu:~# docker ps | awk '{print  $2}'
ID
raintank/proxy
raintank/task-agent
raintank/tsdb-gw
raintank/graphitewatcher
raintank/worldping-api
raintank/statsdaemon
raintank/eventtank
sheepkiller/kafka-manager
cassandra:3.0.8
raintank/graphite
jpodeszwik/kafka-offset-monitor:0.2.1
raintank/rabbitmq
mysql
raintank/task-server
raintank/kafka
raintank/graphite-metrictank
library/elasticsearch:latest
raintank/collectd
root@ubuntu:~# 

Default Grafana Port Not running :
root@ubuntu:~# 
root@ubuntu:~# netstat -antlp | grep 3000
root@ubuntu:~# 

Could you please give some more explanation on this how to connect it. Since I followed the steps mentioned in the README file.

**Comment by Dieterbe** [comment] 2016-10-05 07:45
there was a critical docker error, so none of the stack got brought up.
the docker log may give you more information.
also make sure that before you run launch_dev.sh, you run stop_dev.sh first, because maybe there was still some stuff running. (`docker ps` should show no containers running, before you run launch_dev.sh), i'll add this to the readme to make it clearer.

**Comment by gugansankar** [comment] 2016-10-15 11:09
Sorry for the delay response on this. I just checked this on s fresh Ubuntu instance. No issues on running build and setup script.

But when I run the launch scipt, it stops with below error and no screen session started. 

Grafana port 3000 also not listening.

Creating raintank_graphitemon_1
Creating raintank_collectd_1
Creating raintank_eventtank_1
Creating raintank_statsdaemon_1
Creating raintank_taskServer_1
Creating raintank_metrictank_1
Creating raintank_kafkaOffsetMonitor_1
Creating raintank_rabbitmq_1
Creating raintank_elasticsearch_1
Creating raintank_kafka_1
Creating raintank_mysql_1
Creating raintank_cassandra_1
Creating raintank_graphiteMetrictank_1
Creating raintank_kafkaManager_1
Creating raintank_carbon-relay-ng_1
Creating raintank_taskAgent_1
Creating raintank_tsdbgw_1
Creating raintank_worldpingApi_1
Creating raintank_graphitewatcher_1
Creating raintank_proxy_1

ERROR: for kafkaManager  Cannot start service kafkaManager: driver failed programming external connectivity on endpoint raintank_kafkaManager_1 (8fa059ea3a4d8078521314875be2ff1db921ed1f6ce246878f06276f3a3b1ea6): Error iptables FORWARD: Another app is currently holding the xtables lock; waiting (1s) for it to exit...

ERROR: for metrictank  Cannot start service metrictank: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\"rootfs_linux.go:53: mounting \\\\"/root/raintank-docker/raintank_code/metrictank/build/metrictank\\\\" to rootfs \\\\"/var/lib/docker/aufs/mnt/77b0ba6a5380d242510d14ec316dd260678464aee590d987c5fe3cced2f7bea9\\\\" at \\\\"/var/lib/docker/aufs/mnt/77b0ba6a5380d242510d14ec316dd260678464aee590d987c5fe3cced2f7bea9/usr/bin/metrictank\\\\" caused \\\\"not a directory\\\\"\\"\"\n"
ERROR: Encountered errors while bringing up the project.
root@ubuntu:~/raintank-docker#

**Comment by gugansankar** [comment] 2016-10-17 04:45
@Dieterbe Any chance to check this ?.  Kindly help on this. 

Some of the containers are not started.

**Comment by Dieterbe** [comment] 2016-10-17 08:13
your first error seems like a problem between docker and your firewall. find out what kind of firewall you have running or google for the error.

for the second error, i just pushed a fix, see above mentioned commit

**Comment by gugansankar** [comment] 2016-10-17 10:09
thanks for your fix. Now metrictank container is created. But none of the screensession started.

root@ubuntu:~/raintank-docker# ./launch_dev.sh 
cleaning logs...
docker-compose bringing up containers...
Creating raintank_graphitemon_1
Creating raintank_collectd_1
Creating raintank_eventtank_1
Creating raintank_statsdaemon_1
Creating raintank_kafka_1
Creating raintank_rabbitmq_1
Creating raintank_taskServer_1
Creating raintank_graphiteMetrictank_1
Creating raintank_metrictank_1
Creating raintank_kafkaOffsetMonitor_1
Creating raintank_mysql_1
Creating raintank_cassandra_1
Creating raintank_kafkaManager_1
Creating raintank_elasticsearch_1
Creating raintank_tsdbgw_1
Creating raintank_worldpingApi_1
Creating raintank_graphitewatcher_1
Creating raintank_carbon-relay-ng_1
Creating raintank_benchmark_1
Creating raintank_taskAgent_1
Creating raintank_proxy_1
Creating raintank_grafana_1
starting screen session...
waiting for all 22 containers to run...
waiting for all 22 containers to run...
waiting for all 22 containers to run...
waiting for all 22 containers to run...
waiting for all 22 containers to run...
waiting for all 22 containers to run...

Only getting above message repeatedly.

Also in grafana dashboard, I don't see any plugin for worldping-app.
![selection_001](https://cloud.githubusercontent.com/assets/4958813/19433763/aa3cffa4-947f-11e6-8516-0b90d3407590.png)

checked in grafana docker container, the plugin app folder is  seems empty. 
![selection_002](https://cloud.githubusercontent.com/assets/4958813/19433793/d2379b54-947f-11e6-90c5-c83e0653c1eb.png)

So I tried to install the worldping-app plugin in the server, but grafana-cli command is not found. Will the setup affect if I install the grafana again on the container?

**Comment by Dieterbe** [comment] 2016-10-17 14:22
ok for the first part, i just wrote down what to do at https://github.com/raintank/raintank-docker#when-stuff-goes-wrong (the 4th item), please do that. for the worldping-app stuff, hold on, i'm working on a fix. i'll get back to you soon.

**Comment by gugansankar** [comment] 2016-10-17 14:34
thanks for your kind replies.

As you mentioned, I checked the container status through 'docker ps -a', carbon-relay-ng container got exited. but there is no logs message for it.

Attached screenshot for your ref.

![selection_003](https://cloud.githubusercontent.com/assets/4958813/19441874/ef42aaf2-94a4-11e6-8aa0-be176d97bb7c.png)

**Comment by gugansankar** [comment] 2016-10-17 14:39
even I tried to start it manually, but it failed without any error message.

```
root@ubuntu:~# docker start 45b715aed8e6
45b715aed8e6
root@ubuntu:~# docker logs 45b715aed8e6
root@ubuntu:~#   docker ps -a |  grep 45b715aed8e6
45b715aed8e6        raintank/carbon-relay-ng                "/bin/sh -c '/go/src/"   11 minutes ago      Exited (127) About a minute ago                                                                                                        raintank_carbon-relay-ng_1
root@ubuntu:~# 
```

**Comment by Dieterbe** [comment] 2016-10-17 15:37
ok i just pushed a bunch of fixes. please:
- inside of `raintank-docker` run git pull so that it updates to the last code.
- run ./stop_dev.sh and assure no containers run (with `docker ps`). then rename the `raintank_code` directory to simply `code`.
- running setup_dev.sh and then launch_dev.sh will now put the worldping plugin in place.
- carbon-relay-ng is a special case. please share the contents of logs/carbon-relay-ng.log instead

**Comment by gugansankar** [comment] 2016-10-17 15:45
Ok, will check it.

for carbon-relay-ng issue, Please find the logs below,

root@ubuntu:~/raintank-docker/logs# cat carbon-relay-ng.log 
/bin/sh: 1: /go/src/github.com/graphite-ng/carbon-relay-ng/carbon-relay-ng: not found
root@ubuntu:~/raintank-docker/logs#

**Comment by gugansankar** [comment] 2016-10-17 16:10
Now I can see the worldping plugin in dashboard. but when I click "worldping home" option, I'm getting error messages and also **unable to add endpoints**.

Please find the screenshot below for your reference.

![selection_004](https://cloud.githubusercontent.com/assets/4958813/19445502/296c612a-94b2-11e6-8a96-692738daa8a2.png)

![selection_005](https://cloud.githubusercontent.com/assets/4958813/19445511/2fcadcae-94b2-11e6-98a9-0e14d44c5e0b.png)

**Comment by gugansankar** [comment] 2016-10-18 06:20
once I entered the key  as "changeme", I can see that some requests are triggered. but one request got cancelled. 

http://ip:3000/api/plugin-proxy/raintank-worldping-app/api/grafana-net/profile/org 
 this url request got cancelled.

 Respective error log message for above event,

2016/10/18 06:01:14 http: proxy error: net/http: request canceled
t=2016-10-18T06:01:14+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/profile/org status=500 remote_addr=10.11.12.13 time_ns=124ns size=0
t=2016-10-18T06:01:17+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/profile/org status=401 remote_addr=10.11.12.13 time_ns=892ns size=67
t=2016-10-18T06:01:17+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/login/ping status=401 remote_addr=10.11.12.13 time_ns=1ns size=26

screenshots:
![selection_006](https://cloud.githubusercontent.com/assets/4958813/19466391/30285cd2-9528-11e6-97e9-7b424fa888f9.png)

![selection_007](https://cloud.githubusercontent.com/assets/4958813/19466396/37da1f9c-9528-11e6-933d-7750ca4d483b.png)

**Comment by Dieterbe** [comment] 2016-10-18 09:23
I have pushed the fix for carbon-relay-ng. if you update your raintank-docker, run build_all.sh and launch_dev.sh again it should be fixed. it will now also run differently so that logs/carbon-relay-ng.log will be equivalent to `docker logs <id>`, you will probably have to remove the logs/carbon-relay-ng.log logfile first because it will be owned by root, whereas it should be owned by your user (do this before launch_dev.sh)

as for the WP problems, i'm having similar issues, I opened ticket #84 to track this problem.
It's interesting that the xhr request is canceled.  Can you verify that the xhr requests that succeed go to the same ip/hostname as the xhr request that is canceled, and also note whether they both use http or https.

**Comment by gugansankar** [comment] 2016-10-18 11:34
Tested the setup on new fresh ubuntu OS again.

setup_dev script failed in **Worldping-api and metrictank** section.

```
root@ubuntu:~/raintank-docker# ./setup_dev.sh 
/root/raintank-docker
> processing code for raintank/inspect: no git repo found -> cloning
Cloning into 'raintank/inspect'...
remote: Counting objects: 112, done.
remote: Total 112 (delta 0), reused 0 (delta 0), pack-reused 112
Receiving objects: 100% (112/112), 2.65 MiB | 806.00 KiB/s, done.
Resolving deltas: 100% (53/53), done.
Checking connectivity... done.
> processing code for raintank/fakemetrics: no git repo found -> cloning
Cloning into 'raintank/fakemetrics'...
remote: Counting objects: 94, done.
remote: Total 94 (delta 0), reused 0 (delta 0), pack-reused 94
Unpacking objects: 100% (94/94), done.
Checking connectivity... done.
> processing code for raintank/metrictank: no git repo found -> cloning
fatal: destination path 'raintank/metrictank' already exists and is not an empty directory.
> processing code for raintank/eventtank: no git repo found -> cloning
fatal: destination path 'raintank/eventtank' already exists and is not an empty directory.
> processing code for raintank/worldping-api: no git repo found -> cloning
Cloning into 'raintank/worldping-api'...
remote: Counting objects: 63715, done.
remote: Total 63715 (delta 0), reused 0 (delta 0), pack-reused 63715
Receiving objects: 100% (63715/63715), 95.52 MiB | 8.49 MiB/s, done.
Resolving deltas: 100% (43209/43209), done.
Checking connectivity... done.
> processing code for raintank/raintank-probe: no git repo found -> cloning
Cloning into 'raintank/raintank-probe'...
remote: Counting objects: 569, done.
remote: Total 569 (delta 0), reused 0 (delta 0), pack-reused 569
Receiving objects: 100% (569/569), 3.90 MiB | 1.56 MiB/s, done.
Resolving deltas: 100% (303/303), done.
Checking connectivity... done.
> processing code for raintank/raintank-apps: no git repo found -> cloning
fatal: destination path 'raintank/raintank-apps' already exists and is not an empty directory.
> processing code for raintank/tsdb-gw: no git repo found -> cloning
Cloning into 'raintank/tsdb-gw'...
remote: Counting objects: 201, done.
remote: Total 201 (delta 0), reused 0 (delta 0), pack-reused 201
Receiving objects: 100% (201/201), 35.25 KiB | 0 bytes/s, done.
Resolving deltas: 100% (94/94), done.
Checking connectivity... done.
> processing code for raintank/raintank-worldping-app: no git repo found -> cloning
Cloning into 'raintank/raintank-worldping-app'...
remote: Counting objects: 3610, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 3610 (delta 0), reused 0 (delta 0), pack-reused 3604
Receiving objects: 100% (3610/3610), 3.84 MiB | 1.20 MiB/s, done.
Resolving deltas: 100% (2271/2271), done.
Checking connectivity... done.
> processing code for graphite-ng/carbon-relay-ng: no git repo found -> cloning
Cloning into 'graphite-ng/carbon-relay-ng'...
remote: Counting objects: 1947, done.
remote: Total 1947 (delta 0), reused 0 (delta 0), pack-reused 1947
Receiving objects: 100% (1947/1947), 4.53 MiB | 1.05 MiB/s, done.
Resolving deltas: 100% (996/996), done.
Checking connectivity... done.
> configuring go
> building raintank-apps binaries
package github.com/raintank/raintank-apps/...: /go/src/github.com/raintank/raintank-apps exists but /go/src/github.com/raintank/raintank-apps/.git does not - stale checkout?
/tmp/scripts/setup_dev.sh: line 75: ./scripts/build_all.sh: No such file or directory
> building raintank-probe
make all
make[1]: Entering directory '/go/src/github.com/raintank/raintank-probe'
bash -c "./scripts/build.sh /go/src/github.com/raintank/raintank-probe"
+++ dirname ./scripts/build.sh
++ cd ./scripts
++ pwd
+ DIR=/go/src/github.com/raintank/raintank-probe/scripts
+ cd /go/src/github.com/raintank/raintank-probe/scripts
++ git describe --long --always
+ GITVERSION=1.0.1-1-gc126635
+ SOURCEDIR=/go/src/github.com/raintank/raintank-probe/scripts/..
+ BUILDDIR=/go/src/github.com/raintank/raintank-probe/scripts/../build
+ export CGO_ENABLED=0
+ CGO_ENABLED=0
+ mkdir -p /go/src/github.com/raintank/raintank-probe/scripts/../build
+ rm -rf '/go/src/github.com/raintank/raintank-probe/scripts/../build/*'
+ cd ../
+ go build -ldflags '-X main.GitHash=1.0.1-1-gc126635' -o /go/src/github.com/raintank/raintank-probe/scripts/../build/raintank-probe
make[1]: Leaving directory '/go/src/github.com/raintank/raintank-probe'
> building worldping-api
package github.com/raintank/raintank-apps/pkg/auth: /go/src/github.com/raintank/raintank-apps exists but /go/src/github.com/raintank/raintank-apps/.git does not - stale checkout?
pkg/api/api.go:8:2: cannot find package "github.com/raintank/raintank-apps/pkg/auth" in any of:
    /usr/local/go/src/github.com/raintank/raintank-apps/pkg/auth (from $GOROOT)
    /go/src/github.com/raintank/raintank-apps/pkg/auth (from $GOPATH)
> building metrictank
make: *** No rule to make target 'bin'.  Stop.
> building carbon-relay-ng
root@ubuntu:~/raintank-docker#
```

Launch script at metrictank creation:

```
ERROR: for metrictank  Cannot start service metrictank: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"/root/raintank-docker/code/metrictank/build/metrictank\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/aufs/mnt/b98e64b37f682ba4e6cae95630bbaa0662bf4ee0d94769095ccb7f5fdde9649c\\\\\\\" at \\\\\\\"/var/lib/docker/aufs/mnt/b98e64b37f682ba4e6cae95630bbaa0662bf4ee0d94769095ccb7f5fdde9649c/usr/bin/metrictank\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n"
ERROR: Encountered errors while bringing up the project.
```

**Comment by Dieterbe** [comment] 2016-10-18 16:28
```
 > processing code for raintank/metrictank: no git repo found -> cloning
fatal: destination path 'raintank/metrictank' already exists and is not an empty directory.
> processing code for raintank/eventtank: no git repo found -> cloning
fatal: destination path 'raintank/eventtank' already exists and is not an empty directory.
```

these errors are very weird. can you tell me what is inside the code/metrictank and code/eventtank directories? on a fresh install they should not exist, but at that point in the script they should exist (and be empty directories), and cloning into empty directories should work fine. but it says not an empty directory.. did you run the script previously and maybe abort it or something? let me know what's inside those dirs please :)

**Comment by gugansankar** [comment] 2016-10-19 05:33
sorry for the delay.

there is no files inside those directories. only some subfolders are present. 

No, I haven't terminate the script while its in process. [ Note : I tested the setup on fresh machine ].

root@ubuntu:~/raintank-docker/code# ls metrictank/build/
metrictank
root@ubuntu:~/raintank-docker/code# ls metrictank/build/metrictank/
root@ubuntu:~/raintank-docker/code# 
root@ubuntu:~/raintank-docker/code# ls eventtank/
build
root@ubuntu:~/raintank-docker/code# 
root@ubuntu:~/raintank-docker/code# ls eventtank/build/
root@ubuntu:~/raintank-docker/code# 
root@ubuntu:~/raintank-docker/code#

**Comment by Dieterbe** [comment] 2016-10-19 07:06
I'm very skeptical that this can happen on a fresh install. those files/dirs can't be there yet. they are also not in version control. i just created a new ubuntu 16.04 machine in digitalocean and ran through the steps and everything worked fine: it said `no git repo found -> cloning` for every module, and cloned all the projects fine.

**Comment by gugansankar** [comment] 2016-10-19 07:27
Ok, will clear everything and try it once. let you know if hit with any issues

**Comment by gugansankar** [comment] 2016-10-19 08:26
yes, now launch-dev.sh script is working fine on a fresh machine. but still I'm unable to create endpoints. Getting 401 errors. hope, you are checking it. Kindly let me know once its fixed. Will test it.

Thanks

**Comment by Dieterbe** [comment] 2016-10-19 08:31
Ok i'm going to close this issue since we worked through all the building issues.

for the http 401's, see #84 the workaround for now is to just make an account on grafana.net, and create an api key there (it's free). and just use that key, that should work. (I will also test this). if you have any more issues, please open a new ticket. thanks

**Closed as completed by Dieterbe** 2016-10-19 08:31 UTC

**Comment by gugansankar** [comment] 2016-10-19 09:12
Just one question on this topic,

so creating account in grafana.net and add that key in api tab, won't store those info in local containers. Everything will be in grafana.net and endpoints/events will stores in raintank.io , Am I correct ? .

Any plan, do you have to keep "Account/API key" generating module in this same docker container sets, instead of going to create it on grafana.net ?. Like , some local account//key management container.

**Comment by woodsaj** [comment] 2016-10-19 09:32
@gugansankar The key needs to be authenticated against grafana.net, but once authenticated all of the endpoints, checks and probes created only exist locally within the components deployed by the raintank-docker stack.

We have no plans to remove the dependency of grafana.net.    The raintank-docker stack is an internal tool used for development and testing.  It is not a product we offer and we can't provide support for it.  

We have made all of this code opensource so that others dont need to re-invent the wheel and can take advantage of the work we have already done.  If the stack doesn't meet your needs you are welcome to fork it and make any modifications you want. If those modifications are aligned with our vision for the stack we will happily merge them.

If you are after a supported on-premise version of our Worldping Product, then i welcome you to reach out to us at hello@raintank.io where we can discuss your options.

**Comment by Dieterbe** [comment] 2016-10-19 09:38
to confirm: it will only use grafana.net for authentication. it will use the collector running in the docker stack, and it will save all data locally through the local tsdb, kafka and metrictank. the only thing that is remote is the authentication.
(I just tested it with a grafana.net key and it works)

I think it would be nice to bypass grafana.net authentication. it would help when developing without internet access or for people who want to run entirely self-hosted. see also #75 , but i don't have time to work on something like that.
